### ISSUE TITLE
Planning Phase 1

### ISSUE THREAD

**Issue by ibrahimdenizz** [ibrahimdenizz/hrms#1]
## Description

In this issue, the first phase of the project will be planned.

## TODO

- [x] Planning of employee creation flow.
- [x] Planning of authentication flow.
- [x] Planning of employee password update flow.
- [x] Planning of employee leave request flow. (without approving).
- [x] Planning of employee leave history flow.
- [x] Planning of database design.
- [x] Planning of software architecture.

**Comment by ibrahimdenizz** [comment]
- [ ] Endpointlere akış açıklamaları girilecek (Yazı ya da diagram şeklinde olabilir).
- [ ] Bütün tarihler iso formatına değiştirilicek (Analiz için).
