### ISSUE TITLE
Project Architecture 

### ISSUE THREAD

**Issue by ibrahimdenizz** [ibrahimdenizz/hrms#9]
In this issue, I will plan project architecture.
---
## TODO
- [x] Diagram of layered architecture.
- [x] Diagram of service relations.
- [x] Diagram of example endpoint flow.
- [x] Project folder structure.

**Comment by ibrahimdenizz** [comment]
## Layered Architecture
![layered-architecture](https://github.com/ibrahimdenizz/hrms/assets/58088365/fb8a8dfa-1e49-4bed-a549-fd6d9d88241a)

**Comment by ibrahimdenizz** [comment]
## Service Relations
![service-relation](https://github.com/ibrahimdenizz/hrms/assets/58088365/670cdcd7-6840-433a-96e8-29f7428f702a)

**Comment by ibrahimdenizz** [comment]
## Module Structure
├── module
│   ├── config
│   ├── controller
│   ├── filter
│   ├── model
│   │   ├── dto
│   │   │   ├── request
│   │   │   ├── response
│   │   │   ├── domain
│   │   ├── entity
│   │   ├── enums
│   │   ├── mapper
│   ├── repository
│   │   ├── <repository-name>
│   ├── serivce
│   │   ├── <service-name>
│   ├── util
│   ├── exception
